openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: YouTube Analytics API
  description: Retrieves your YouTube Analytics data.
  version: v2
  x-discovery-doc-revision: '20230103'
  x-generated-date: '2023-01-05'
servers:
  - url: https://youtube.googleapis.com
  - url: https://youtubeanalytics.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/youtubepartner: View and manage your assets and associated content on YouTube
            https://www.googleapis.com/auth/youtube: Manage your YouTube account
            https://www.googleapis.com/auth/yt-analytics-monetary.readonly: >-
              View monetary and non-monetary YouTube Analytics reports for your
              YouTube content
            https://www.googleapis.com/auth/youtube.readonly: View your YouTube account
            https://www.googleapis.com/auth/yt-analytics.readonly: View YouTube Analytics reports for your YouTube content
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
paths:
  /v2/groups:
    post:
      description: Creates a group.
      operationId: youtubeAnalytics.groups.insert
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
    put:
      description: Modifies a group. For example, you could change a group's title.
      operationId: youtubeAnalytics.groups.update
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
    get:
      description: >-
        Returns a collection of groups that match the API request parameters.
        For example, you can retrieve all groups that the authenticated user
        owns, or you can retrieve one or more groups by their unique IDs.
      operationId: youtubeAnalytics.groups.list
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
    delete:
      description: Deletes a group.
      operationId: youtubeAnalytics.groups.delete
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
  /v2/groupItems:
    delete:
      description: Removes an item from a group.
      operationId: youtubeAnalytics.groupItems.delete
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
    get:
      description: >-
        Returns a collection of group items that match the API request
        parameters.
      operationId: youtubeAnalytics.groupItems.list
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
    post:
      description: Creates a group item.
      operationId: youtubeAnalytics.groupItems.insert
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly
  /v2/reports:
    get:
      description: Retrieve your YouTube Analytics reports.
      operationId: youtubeAnalytics.reports.query
      tags: []
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/youtube
          Oauth2c:
            - https://www.googleapis.com/auth/youtube
        - Oauth2:
            - https://www.googleapis.com/auth/youtube.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/youtube.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/youtubepartner
          Oauth2c:
            - https://www.googleapis.com/auth/youtubepartner
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/yt-analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/yt-analytics.readonly